version: '3'
services:
  rent-postgres:
    image: postgres:16
    container_name: postgres-rentdb
    environment:
      POSTGRES_USER: "rentdb"
      POSTGRES_PASSWORD: "rentdb"
      POSTGRES_DB: "rent"
    volumes:
      - ./create-tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    ports:
      - 5441:5432
    networks:
      - rent-network
    
  rent-mosquitto:
    image: eclipse-mosquitto
    container_name: rent-mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - rent-network

  rent-backend:
    build: .
    container_name: rent-backend
    command: python3 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - rent-network
    depends_on:
      - rent-postgres
      - rent-mosquitto
    environment:
      DATABASE_URL: postgres://rentdb:rentdb@rent-postgres/rent

volumes:
  config:
  data:
  log:

networks:
  rent-network:
    name: rent-network
    driver: bridge